version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --spider http://localhost:11434 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 300s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_NUM_GPU=100

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - openwebui:/app/backend/data
      - ./notes:/docs
      - ./faiss_index:/app/faiss_index
    command: /app/entrypoint.sh
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama:
  openwebui:
